#!/usr/bin/env bash

# https://github.com/asyrjasalo/rfdocker
# https://hub.docker.com/r/robotframework/rfdocker

set -e

### constants ##################################################################

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

### variables ##################################################################

: "${BUILD_ARGS:=""}"
: "${BUILD_DIR:="$this_path"}"
: "${BUILD_NAME:="$(date -u +%Y.%m.%d.post%H%M%S.dev"$(id -u)")"}"
: "${IMAGE_NAME:="${this_path##*/}"}"
: "${RUN_ARGS:=""}"

### build and run ##############################################################

docker-compose -f ${this_path}/../../docker-compose-util.yml build robot

docker-compose -f ${this_path}/../../docker-compose-util.yml run --rm robot
